### ISSUE TITLE
Build failing due to skipped (but available) dependencies

### ISSUE THREAD

**Issue by vivekbhr** [krlmlr/r-appveyor#107]
Hi

[Here's my build report](https://ci.appveyor.com/project/vivekbhr/icetea/build/1.0.6#L181)

The error:

```
* checking package dependencies ... ERROR
Package required but not available: 'TxDb.Dmelanogaster.UCSC.dm6.ensGene'
```

which is due to line 180 : 

```
Rscript -e 'if (!("remotes" %in% rownames(installed.packages()))) q(status=1)'
+ Rscript -e 'options(repos=c(CRAN="https://cran.rstudio.com")); remotes::install_deps(dependencies = TRUE, type="both")'
Skipping 3 packages not available: GenomeInfoDbData, Rsubread, TxDb.Dmelanogaster.UCSC.dm6.ensGene
```

My build fails as the required dependency `GenomeInfoDbData` and `TxDb.Dmelanogaster.UCSC.dm6.ensGene` are apparently not available. But I can install them on my windows desktop with the same architecture. I don't know whether it's an issue with `remotes` (ping @gaborcsardi ).

Any help appreciated. Thanks

**Comment by gaborcsardi** [comment]
This was fixed in `remotes`. To enable falling back to source packages, you need to set the `R_COMPILE_AND_INSTALL_PACKAGES` environment variable to `always`.

@krlmlr maybe it would make sense to set it by default?

**Comment by krlmlr** [comment]
Thanks for pointing me to this env var. For now I'd rather document it in the README of this repo. PR welcome!

**Comment by vivekbhr** [comment]
@gaborcsardi This change from `remotes` is not yet in the cran release so my build is still failing. Is there a way to point r-appveyor to use `remotes` from github?

**Comment by krlmlr** [comment]
You might be able to install it manually from your `appveyor.yml`.

**Comment by vivekbhr** [comment]
@krlmlr @gaborcsardi I tried installing it manually but failed with this message 

```
Downloading GitHub repo gaborcsardi/remotes@master
185Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
186  cannot open URL 'https://api.github.com/repos/gaborcsardi/remotes/zipball/master'
```


My [appveyor.yml](https://github.com/vivekbhr/icetea/blob/master/appveyor.yml)
My [build report](https://ci.appveyor.com/project/vivekbhr/icetea/build/1.0.22)

Is that an issue with my config?

**Comment by gaborcsardi** [comment]
My guess is a GitHub rate limiting problem. Here is another way to install it: 

```r
source("https://install-github.me/r-lib/remotes")
```

**Comment by vivekbhr** [comment]
I added  `R CMD source("https://install-github.me/r-lib/remotes")` 
I got : 
```
137 'source' is not recognized as an internal or external command,
138 operable program or batch file.
139 Command exited with code 1
```

**Comment by gaborcsardi** [comment]
This is how to run an R script from the command line:
```
Rscript -e 'source(...)'
```

**Comment by vivekbhr** [comment]
sorry i figures this one .. never mind

**Comment by vivekbhr** [comment]
Thank you @gaborcsardi and @krlmlr . my build is passing now
